import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Header from "../components/header";
import Footer from "../components/footer";
import QuickLinks from "../components/quick-links";
import { SpecProvider } from "../contexts/SpecContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SpecProvider>
          <div className="max-w-[1728px] mx-auto px-2 sm:px-4">
            <Header />
            <main className="relative z-0">{children}</main>
            <Footer />
            <QuickLinks />
          </div>
        </SpecProvider>
      </body>
    </html>
  );
}
